# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\TSiSA_UI4.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_alt(object):
    def setupUi(self, Window_alt):
        Window_alt.setObjectName("Window_alt")
        Window_alt.resize(332, 359)
        Window_alt.setStyleSheet("background-color: rgb(153, 255, 148);")
        self.centralwidget = QtWidgets.QWidget(Window_alt)
        self.centralwidget.setObjectName("centralwidget")
        self.info_button = QtWidgets.QPushButton(self.centralwidget)
        self.info_button.setGeometry(QtCore.QRect(310, 0, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.info_button.setFont(font)
        self.info_button.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.info_button.setObjectName("info_button")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 258, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setStyleSheet("background-color: rgb(211, 255, 211);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.btn_save = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_save.setStyleSheet("background-color: rgb(164, 170, 255);")
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout.addWidget(self.btn_save)
        Window_alt.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_alt)
        QtCore.QMetaObject.connectSlotsByName(Window_alt)

    def retranslateUi(self, Window_alt):
        _translate = QtCore.QCoreApplication.translate
        Window_alt.setWindowTitle(_translate("Window_alt", "MainWindow"))
        self.info_button.setText(_translate("Window_alt", "i"))
        self.label.setText(_translate("Window_alt", "Альтернатива 1"))
        self.btn_save.setText(_translate("Window_alt", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_alt = QtWidgets.QMainWindow()
    ui = Ui_Window_alt()
    ui.setupUi(Window_alt)
    Window_alt.show()
    sys.exit(app.exec_())
