# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\TSiSA_UI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_stap2(object):
    def setupUi(self, Window_stap2):
        Window_stap2.setObjectName("Window_stap2")
        Window_stap2.resize(340, 360)
        Window_stap2.setStyleSheet("background-color: rgb(153, 255, 148);")
        self.centralwidget = QtWidgets.QWidget(Window_stap2)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(86, 100, 167, 173))
        self.tableWidget.setStyleSheet("background-color: rgb(211, 255, 211);")
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(21)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(125, 30, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(70, 310, 200, 40))
        self.btn_save.setStyleSheet("background-color: rgb(164, 170, 255);")
        self.btn_save.setObjectName("btn_save")
        self.info_button = QtWidgets.QPushButton(self.centralwidget)
        self.info_button.setGeometry(QtCore.QRect(315, 0, 20, 20))
        self.info_button.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.info_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\299086_info_sign_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_button.setIcon(icon)
        self.info_button.setObjectName("info_button")
        Window_stap2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_stap2)
        QtCore.QMetaObject.connectSlotsByName(Window_stap2)

    def retranslateUi(self, Window_stap2):
        _translate = QtCore.QCoreApplication.translate
        Window_stap2.setWindowTitle(_translate("Window_stap2", "Групповой парный анализ - Шаг 2"))
        self.label.setText(_translate("Window_stap2", "Эксперт 1"))
        self.btn_save.setText(_translate("Window_stap2", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_stap2 = QtWidgets.QMainWindow()
    ui = Ui_Window_stap2()
    ui.setupUi(Window_stap2)
    Window_stap2.show()
    sys.exit(app.exec_())
