# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\TSiSA_UI3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_stap3(object):
    def setupUi(self, Window_stap3):
        Window_stap3.setObjectName("Window_stap3")
        Window_stap3.resize(310, 420)
        Window_stap3.setStyleSheet("background-color: rgb(153, 255, 148);")
        self.centralwidget = QtWidgets.QWidget(Window_stap3)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(55, 10, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(71, 40, 192, 173))
        self.tableWidget.setStyleSheet("background-color: rgb(211, 255, 211);")
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(21)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(69, 230, 172, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(71, 270, 192, 53))
        self.tableWidget_2.setStyleSheet("background-color: rgb(211, 255, 211);")
        self.tableWidget_2.setRowCount(1)
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(21)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 350, 250, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(125, 380, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(211, 255, 211);")
        self.label_4.setObjectName("label_4")
        Window_stap3.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_stap3)
        QtCore.QMetaObject.connectSlotsByName(Window_stap3)

    def retranslateUi(self, Window_stap3):
        _translate = QtCore.QCoreApplication.translate
        Window_stap3.setWindowTitle(_translate("Window_stap3", "Групповой парный анализ - Шаг 3"))
        self.label.setText(_translate("Window_stap3", "Обобщённая матрица"))
        self.label_2.setText(_translate("Window_stap3", "Ранги альтернатив"))
        self.label_3.setText(_translate("Window_stap3", "Коэффициент конкордации"))
        self.label_4.setText(_translate("Window_stap3", "0.0000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_stap3 = QtWidgets.QMainWindow()
    ui = Ui_Window_stap3()
    ui.setupUi(Window_stap3)
    Window_stap3.show()
    sys.exit(app.exec_())
