# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\TSiSA_UI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_stap2(object):
    def setupUi(self, Window_stap2):
        Window_stap2.setObjectName("Window_stap2")
        Window_stap2.resize(332, 354)
        Window_stap2.setStyleSheet("background-color: rgb(153, 255, 148);")
        self.centralwidget = QtWidgets.QWidget(Window_stap2)
        self.centralwidget.setObjectName("centralwidget")
        self.info_button = QtWidgets.QPushButton(self.centralwidget)
        self.info_button.setGeometry(QtCore.QRect(310, 0, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.info_button.setFont(font)
        self.info_button.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.info_button.setObjectName("info_button")
        self.info_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.info_button_2.setGeometry(QtCore.QRect(280, 330, 51, 20))
        self.info_button_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.info_button_2.setObjectName("info_button_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 258, 351))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tableWidget.setStyleSheet("background-color: rgb(211, 255, 211);")
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(21)
        self.verticalLayout.addWidget(self.tableWidget)
        self.btn_save = QtWidgets.QPushButton(self.widget)
        self.btn_save.setStyleSheet("background-color: rgb(164, 170, 255);")
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout.addWidget(self.btn_save)
        Window_stap2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_stap2)
        QtCore.QMetaObject.connectSlotsByName(Window_stap2)

    def retranslateUi(self, Window_stap2):
        _translate = QtCore.QCoreApplication.translate
        Window_stap2.setWindowTitle(_translate("Window_stap2", "Групповой парный анализ - Шаг 2"))
        self.info_button.setText(_translate("Window_stap2", "i"))
        self.info_button_2.setText(_translate("Window_stap2", "Criteria"))
        self.label.setText(_translate("Window_stap2", "Эксперт 1"))
        self.btn_save.setText(_translate("Window_stap2", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_stap2 = QtWidgets.QMainWindow()
    ui = Ui_Window_stap2()
    ui.setupUi(Window_stap2)
    Window_stap2.show()
    sys.exit(app.exec_())
